import Head from 'next/head'
import unfetch from 'isomorphic-unfetch'
import slug from 'slug'
import Image from 'next/image'


export default function Home({ movie }) {
    const image = () => `https://image.tmdb.org/t/p/w500${movie.poster_path}`

    return (
        <div >
            <Head>
                <title>{movie.original_title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='flex flex-col '>
                <div className='flex justify-center'>
                    <Image
                        className='rounded-2xl'
                        loader={image}
                        src="me.png"
                        alt="Picture of the author"
                        width={400}
                        height={500}
                    />
                </div>
                <div className='flex flex-col items-center mt-4'>
                    <div className='text-white text-2xl'>{movie.original_title}</div>
                    <div className='text-white p-10 text-justify'>{movie.overview}</div>
                </div>

            </div>
        </div>
    )
}

export async function getStaticPaths() {
    const data = await unfetch(`https://api.themoviedb.org/3/trending/movie/week?api_key=${process.env.REACT_APP_API_KEY}&language=tr`)
    const movies = await data.json()
    const paths = movies.results.map(movie => {
        return { params: { slug: `${slug(`${movie.original_title}`)}_${movie.id}` } }
    })

    return {
        paths,
        fallback: false
    };
}


export async function getStaticProps({ params }) {
    const id = params.slug.split('_')[1]
    const data = await unfetch(`https://api.themoviedb.org/3/movie/${id}?api_key=${process.env.REACT_APP_API_KEY}&language=tr-TR`)
    const movie = await data.json()
    return {
        props: {
            movie
        },
    }
}