import Head from 'next/head'
import unfetch from 'isomorphic-unfetch'
import Link from 'next/link'
import slug from 'slug'
import CardMovie from '../components/CardMovie'
import { useState, useEffect } from 'react'
import { useBase } from '../context/BaseContext'

export default function Home({ movies }) {
  const { search, setSearch } = useBase()
  const [res, setRes] = useState([])

  function update(event) {
    setSearch(event.target.value);
    if (typeof onChange === "function") {
      onChange(event.target.value);
    }
  }

  useEffect(async () => {
    const data = await unfetch(`https://api.themoviedb.org/3/search/movie?api_key=${process.env.REACT_APP_API_KEY}&language=tr-TR&query=${search}&page=1&include_adult=false`)
    const cevap = await data.json()
    setRes(cevap);
  }, [search])


  return (
    <div className='container h-screen'>
      <Head>
        <title>Filmtika || MK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex justify-center mb-6'>
        <input className='outline-none py-2 px-5 rounded-full' placeholder='Search...' type="text" value={search} onChange={update} />
      </div>



      {
        search.length > 1 ?
          <div className='sm:flex sm:flex-wrap sm:justify-between'>
            <div className='sm:flex sm:flex-wrap sm:justify-between'>
              {
                res.results.map((movie, id) => (
                  <CardMovie key={id} {...movie} />
                ))
              }
            </div>
          </div>
          :
          <div className='flex flex-col items-center'>
            <div className='flex justify-center'>
              <h2 className='text-white text-2xl sm:text-3xl'>Bu haftanın Trendleri</h2>
            </div>
            <div className=' sm:flex sm:flex-wrap sm:justify-between'>
              {
                movies.results.map((movie, id) => (
                  <Link key={id} href="/movie/[slug]" as={`/movie/${slug(`${movie.original_title}`)}_${movie.id}`}>
                    <a> <CardMovie {...movie} /> </a>
                  </Link>

                ))
              }
            </div>
          </div>
      }
    </div>
  )
}



export async function getStaticProps() {
  const data = await unfetch(`https://api.themoviedb.org/3/trending/movie/week?api_key=${process.env.REACT_APP_API_KEY}&language=tr`)

  const movies = await data.json()
  return {
    props: {
      movies
    },
  }
}